const CONSTANTS = {};
CONSTANTS.COSMOS = {};
CONSTANTS.ENDPOINT = {};

CONSTANTS.PORT = process.env.PORT || "3001";
CONSTANTS.ENDPOINT.LIST = "/list";

CONSTANTS.ENDPOINT.MASTERDETAIL = "/masterdetail";

CONSTANTS.ENDPOINT.GRID = "/grid";


CONSTANTS.COSMOS.COLLECTION = "ListItems";
module.exports = CONSTANTS;
